export const countries = [
    "Armenia",
    "Russia",
    "USA",
    "Canada",
    "England",
    "Poland",
    "France",
    "Spain",
    "Italy",
    "Tunis",
    "Georgia",
    "Australia",
    "Brazil",
    "Germany",
    "Japan",
    "China",
    "India",
    "Mexico",
    "South Africa",
    "Argentina",
    "Egypt",
    "South Korea",
    "Turkey",
    "Nigeria",
    "Indonesia",
    "Saudi Arabia",
    "Vietnam",
    "Thailand",
    "Greece",
    "Sweden",
    "Norway",
    "Netherlands",
    "Belgium",
    "Switzerland",
    "Austria",
    "Denmark",
    "Finland",
    "Portugal",
    "Ireland",
    "New Zealand",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Ukraine",
    "Malaysia",
    "Singapore",
    "Philippines",
    "Pakistan",
    "Bangladesh",
    "Kenya",
    "Iran",
    "Iraq",
    "Israel",
    "Morocco",
    "Algeria",
    "Chile",
    "Colombia",
    "Peru",
    "Venezuela",
    "Cuba",
    "Ecuador",
    "Bolivia",
    "Paraguay",
    "Uruguay",
    "Panama",
    "Costa Rica",
    "Nicaragua",
    "Honduras",
    "El Salvador",
    "Guatemala",
    "Jamaica",
    "Haiti",
    "Dominican Republic",
    "Trinidad and Tobago",
    "Barbados",
    "Bahamas",
    "Samoa",
    "Tonga",
    "Vanuatu",
    "Papua New Guinea",
    "Solomon Islands",
    "Mauritius",
    "Madagascar",
    "Seychelles",
    "Comoros",
    "Cyprus",
    "Malta",
    "Iceland",
    "Greenland",
    "Fiji",
    "Belize",
    "Guyana",
    "Suriname",
    "French Guiana",
    "Congo",
    "Gabon",
    "Cameroon",
    "Senegal",
    "Mali",
    "Niger",
    "Benin",
    "Togo",
    "Ghana",
    "Libya",
    "Somalia",
    "Ethiopia",
    "Eritrea",
    "Djibouti",
    "Central African Republic",
    "Equatorial Guinea",
    "Sierra Leone",
    "Liberia",
    "Ivory Coast",
    "Guinea",
    "Guinea-Bissau",
    "Gambia",
    "Burkina Faso",
    "Cape Verde",
    "Mauritania",
    "Lesotho",
    "Swaziland",
    "Namibia",
    "Botswana",
    "Zimbabwe",
    "Zambia",
    "Angola",
    "Malawi",
    "Mozambique",
    "Tanzania",
    "Uganda",
    "Rwanda",
    "Burundi",
    "South Sudan",
    "Sudan",
    "Yemen",
    "Oman",
    "Jordan",
    "Lebanon",
    "Kuwait",
    "Qatar",
    "Bahrain",
    "United Arab Emirates",
    "Afghanistan",
    "Sri Lanka",
    "Nepal",
    "Bhutan",
    "Maldives",
    "Myanmar",
    "Laos",
    "Cambodia",
    "Brunei",
    "Timor-Leste",
    "Mongolia",
    "North Korea",
    "Taiwan",
    "Turkmenistan",
    "Uzbekistan",
    "Kyrgyzstan",
    "Kazakhstan",
    "Tajikistan",
    "Liechtenstein",
    "Monaco",
    "Andorra",
    "San Marino",
    "Vatican City"
];
